### ISSUE TITLE
When selecting e.g. standards or subjects, the button text is very large, but also hard to see

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/FAIRsharing-Assistant#103]
On my laptop, it is very hard to see the "Select" and "skip" buttons after starting to type into the text box
![image](https://github.com/FAIRsharing/FAIRsharing-Assistant/assets/143586/97500245-88b3-4157-8f86-db46a75e8a7d)

Also, once I start typing I have to scroll past the selection pulldown to get back to these buttons and to the general explanatory text, which isn't ideal.

1. Is there any way to make these buttons always visible? Perhaps put them to the right of the pulldown, and have the pulldown only take e.g. 50% of the width of the window? I realise this may lead to horizontal scrolling issues. Perhaps there is a more compact way of showing the search results?
2. Is there any way to reduce the size of these buttons as there appears to be a lot of space around the words Select and Skip?

Finally, the multiple-select is fantastic. What is the behaviour of the query, I'm guessing it's an "OR" linking any of the standards types? If so, let me know and I will update the explanatory text accordingly.

The one issue I have from a UI perspective is that you can't see what you have already selected if you start typing a second search term, and so you aren't sure if the selection has been retained. Is there a way for each selection to appear somewhere to show those that have already been selected and possibly allow removal of individual terms as well? A bit like what was done in the older assistant tag search interface.

Thanks!

**Comment by knirirr** [comment]
>     1. Is there any way to make these buttons always visible? Perhaps put them to the right of the pulldown, and have the pulldown only take e.g. 50% of the width of the window? I realise this may lead to horizontal scrolling issues. Perhaps there is a more compact way of showing the search results?

Not really.

>     2. Is there any way to reduce the size of these buttons as there appears to be a lot of space around the words Select and Skip?

That would be addressed by https://github.com/FAIRsharing/FAIRsharing-Assistant/issues/100; these question cards need some work doing to make them an appropriate size whilst having the text clearly visible. 

> Finally, the multiple-select is fantastic. What is the behaviour of the query, I'm guessing it's an "OR" linking any of the standards types? If so, let me know and I will update the explanatory text accordingly.

Yes, that's correct. 

> Is there a way for each selection to appear somewhere to show those that have already been selected and possibly allow removal of individual terms as well? A bit like what was done in the older assistant tag search interface.

I could import the same component used by the main search interface, but that would take up a lot of space.
Or, mix the tags, independent of type, in the same row above the selection box (taking up some space, but less).

**Comment by allysonlister** [comment]
Thanks for all of your replies. I think your second option is great, "mix the tags, independent of type, in the same row above the selection box (taking up some space, but less)."

**Comment by knirirr** [comment]
These issues have been dealt with now (though improving the question card text still has an open ticket).
