### ISSUE TITLE
Clicking on breadcrumbs doesn't reset that value.

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/FAIRsharing-Assistant#106]
I'm at this stage of the assistant (note breadcrumbs for details)
![image](https://github.com/FAIRsharing/FAIRsharing-Assistant/assets/143586/b975ce64-2108-40ee-9e67-84c57185ff59)

Let's imagine that I think I'll choose based on research area / subject next:
![image](https://github.com/FAIRsharing/FAIRsharing-Assistant/assets/143586/a51076e7-19fe-4738-9ebc-ad8294f2c880)

But then I decide I want to change my answer, so I click on "Deposit data" breadcrumb:
![image](https://github.com/FAIRsharing/FAIRsharing-Assistant/assets/143586/8f269c1e-67b3-40b5-962c-a61643ae3a35)

Note that I still have only 5 records - clicking on any breadcrumb should result in the resetting of the "basket" of results to whatever applied at that time; in the above case, repositories or kb/repo AND ready or In development

**Comment by knirirr** [comment]
I'm aware of this one and still trying to come up with a solution. 
Currently, going back to a breadcrumb from before any records were selected will clear them from the result store, but the intermediate stages are somewhat harder.
