### ISSUE TITLE
Only applicable subjects/domains/taxonomies should be available in pulldown

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/FAIRsharing-Assistant#107]
All subjects are allowed in pulldown, irrespective of the current result set. e.g. in the following setup:
![Screenshot from 2023-10-24 13-21-06](https://github.com/FAIRsharing/FAIRsharing-Assistant/assets/143586/58398cf5-c684-48d4-adf0-afa8e3cfbbac)
...I can still select ALL subjects, domains and taxonomies. This is confusing for the user, who may then select tags that aren't even listed in their result set. I'm not sure of the best way to resolve this, and am agnostic about the way it is resolved. Ideally, only those tags that are...

1. present in the records of the record set
2. are in the hierarchy directly above any of the tags that are in point 1 above

...should be accessible to the user in this page.

**Comment by knirirr** [comment]
Sorry, I can't do anything about this at this stage. This will have to be put on hold until I can work out how/if it might be possible.

**Comment by knirirr** [comment]
Surprisingly, I have managed to work out a way to do this, at the inevitable cost of additional time spent loading data.
