### ISSUE TITLE
Select/skip => Replace with "continue"

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/FAIRsharing-Assistant#109]
There are currently two questions, e.g. "Is your data in any particular format or tagged with an particular terminology?" where users will be invited to select things (formats or tags) to narrow down their selection before they move on. These questions have "select" and "skip" buttons. 

For the format/terminology question, "select" will apply the filter and "skip" will move on without applying it. The user won't know how many records they'll end up with until they move to the next question.

For subjects, domains etc., each selection will run a query and change the count of records found as the user interacts with the site. Deleting all selected tags will return the selection to the default of all ready databases that they got when choosing to be a researcher looking to deposit data. Therefore, the "select" and "skip" buttons both do the same thing, which is to move to the next question with the results as they currently are.

I think it would be better to harmonise the behaviour of these two questions, and I'm in favour of the way the second one works, but _replacing both "select" and "skip" with "continue"_. 

In this case the descriptive text would be modified to let users know they may simply continue without changing anything, or they can make all the selections they like, then continue.

**Comment by allysonlister** [comment]
Thank you - I would also be in favour of the second option as described above.
