### ISSUE TITLE
General updates to researchers and dev/curators in the mock-up slides

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/FAIRsharing-Assistant#110]
Hi all,

I've updated the mock-up slides as much as I'll be able to this week as I need to move onto other topics. Please take a good look as there are a number of differences to the previous version:

1. incorporation of the design choices currently in the assistant (looking great!)
2. changing a lot of the text
3. removal of one of the steps in the researcher route that was talking about relations to journal and funder policies (wait until more policy curation has happened before putting this step back in)
4. Better explanation of behaviour etc.
5. Note that the breadcrumbs should be incorporated into sentences such that they can be easily copied by the user to create summary text of their search results; this will be great for copying into their own documentation etc to remind them of what they did to get to the result set they choose/download. There are example sentences in the slides.

Broadly speaking, I've updated the researcher route and added a developer/curator route.

Thanks!

**Comment by knirirr** [comment]
As far as I'm aware this is complete, with the caveat that the slides are an approximation and the implementation may not exactly match them. 

At this stage I think the following remain:

* Tidying up CSS, layouts etc.
* Adding more questions.
* Finding bugs.

I'll add tickets as appropriate.
