### ISSUE TITLE
Replace "copy" button with "route summary" (or similar)

### ISSUE THREAD

**Issue by knirirr** [FAIRsharing/FAIRsharing-Assistant#112]
Instead of copying the breadcrumb trail directly, that button could be repurposed to generate a summary of where the user currently is. 
One issue to solve would be the best way of storing the text for each combination of route keys (perhaps a separate JSON file to reduce question file clutter), and to replace strings in it with data stored in breadcrumbs. 
If possible, a display of this text between the breadcrumbs and the rest of the page (or a tooltip), and at the top of the results preview page, would be good. 

Here's a summary of some text to display:

| Breadcrumb trail | Summary text |
| ---------------------- | -------------------|
| Start | Start answering the Assistant’s questions to get a tailored set of FAIRsharing records relevant to your needs. Learn more [about FAIRsharing](https://fairsharing.org/educational). |
| Researcher | The FAIRsharing Assistant is set to a Researcher role. Learn how FAIRsharing can [help researchers](https://fairsharing.org/educational#researchers). |
| Researcher -> Deposit data | The FAIRsharing Assistant is set to a Researcher role. We have restricted the available databases to those appropriate for data deposition, which means they: are repositories or knowledgebases/repositories, have a life cycle status of Ready or In development. Learn about the FAIRsharing [database registry](https://fairsharing.org/educational#databases), and how FAIRsharing can [help researchers](https://fairsharing.org/educational#researchers). |
| Researcher -> Deposit data -> according to own needs | The FAIRsharing Assistant is set to a Researcher role. We have restricted the available databases to those appropriate for data deposition, which means they: are repositories or knowledgebases/repositories, have a life cycle status of Ready or In development. The next step is to list any standards that might be relevant to your deposition requirements. Learn about the FAIRsharing [databases](https://fairsharing.org/educational#databases) and [standards](https://fairsharing.org/educational#standards) in FAIRsharing, and how FAIRsharing can [help researchers](https://fairsharing.org/educational#researchers). |

**Comment by knirirr** [comment]
Would the rows you'd add contain any reference to options the users would have selected, e.g. a subject/domain tags, etc.? This would have some bearing on how this might work.

**Comment by allysonlister** [comment]
Yes, that's the plan. I was intending to add that to the table text, but didn't get that far today before I finished for the day. Thanks!

**Comment by knirirr** [comment]
This has been done and awaits completion of text as new questions are also added. So, this ticket may now be closed.
