### ISSUE TITLE
Removing banner on the start page

### ISSUE THREAD

**Issue by prakhyatox** [FAIRsharing/FAIRsharing-Assistant#115]
Removal of the alert massage when the user is on the '''Start Page```

![image](https://github.com/FAIRsharing/FAIRsharing-Assistant/assets/109139583/6f3fc755-a486-4768-bf80-ee2d1df3cdff)

**Comment by knirirr** [comment]
I'm having some trouble reproducing this. Do you recall the sequence in which you navigated through this?

**Comment by prakhyatox** [comment]
I am also not able to replicate it now. Therefore, closing this issue
