### ISSUE TITLE
Text-based update and button colours

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/FAIRsharing-Assistant#27]
Please could you update the following?

### /researchfields
Title: Define your area of research
Subtitle: By selecting the relevant subjects, domains and (if applicable) taxonomy, the Assistant will narrow your search to the records that most closely match your needs.

### /refineregistry
Title: Define the type and characteristics of the [standards|databases|policies]
Subtitle: By selecting relevant values, the Assistant will narrow your search to the records that most closely match your needs.

Also, separately, and as time permits: please change the four action button colours to two other palette colours so they don't match the content tags, as this could be confusing.
![image](https://github.com/FAIRsharing/FAIRsharing-Assistant/assets/143586/58dee7ad-c020-4319-bcc8-c8945374298a)

**Comment by knirirr** [comment]
This has been deployed.
