### ISSUE TITLE
Policy registry filters

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/FAIRsharing-Assistant#38]
![image](https://github.com/FAIRsharing/FAIRsharing-Assistant/assets/143586/a97ab771-8501-4f2b-8b6e-ee2fbf3cf4ea)
When choosing the policy route, and then selecting "yes" for "recommends at least one standard", the number of policies drops from 169 to 0. When doing the same for "recommends at least one database", it drops to 1. Both are inaccurate, as are the "no" values for both filters, which return 2 and 1, respectively.

Thanks!

**Comment by knirirr** [comment]
This isn't a bug; I haven't yet had chance to run an reindex on the main FAIRsharing site.
@allysonlister when would suit? it will now require an outage of approx. 10 minutes IIRC?

**Comment by allysonlister** [comment]
That sounds good - thanks!
