### ISSUE TITLE
Technical implementation of user scenarios

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/FAIRsharing-Assistant#39]
During August, please could you review the user scenarios linked via the dev meeting notes (I'll continue updating them this week), and consider the best way to technically implement them. When I'm back in September, we can review your thoughts and any implementation options you've come up with, and decide what to keep; nothing will go into production during August though!

**Comment by knirirr** [comment]
This has been dealt with by recent revisions to questions.
