### ISSUE TITLE
Adding Beta to the title in the FAIRsharing Assistant.

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/FAIRsharing-Assistant#40]
Susanna would like to the addition of the word/character for "beta" after the title "FAIRsharing Assistant" at the top (in addition to the sentence in the footer).

**Comment by Prakhyat2589** [comment]
@allysonlister 

Please confirm from the following option below

1. FAIRsharing Assistant Beta

2. <sup>β</sup>FAIRsharing Assistant

3. FAIRsharing Assistant<sup>β</sup>

**Comment by allysonlister** [comment]
Just item 1 I think, thank you! But can Beta be in a different font or size or italicised or colour; just to differentiate it? Let me know what you think.

**Comment by prakhyatox** [comment]
Will this work?

![image](https://github.com/FAIRsharing/FAIRsharing-Assistant/assets/109139583/61e5c432-101a-4037-ba98-f156382e1555)

**Comment by allysonlister** [comment]
The style of the word is great - please can you change its colour so it stands out from the main name of the assistant, e.g. our 'maroon' colour?

**Comment by prakhyatox** [comment]
How about green?

![image](https://github.com/FAIRsharing/FAIRsharing-Assistant/assets/109139583/fae47fd6-5ea2-45ad-b7cd-8859fe4e7bef)
