### ISSUE TITLE
Clearing all selections from results page no longer behaves as expected

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/FAIRsharing-Assistant#98]
Here's a research route I took:

![image](https://github.com/FAIRsharing/FAIRsharing-Assistant/assets/143586/4200fe6b-9474-4da6-9186-47f9e7575aad)

I'm viewing the 7 results, but now want to get back to beginning of the researcher route. It appears my only option is to 'clear all selections', which takes me back to the page that is now reached only by the 'search directly' button. Instead, I would expect it to take me back,to https://deploy-preview-97--fairassist.netlify.app/0 . When I try to get back by choosing 'Home', I do go back to the front page, but all of my selections are still in place; they should be cleared:
![image](https://github.com/FAIRsharing/FAIRsharing-Assistant/assets/143586/d93a2692-60e4-4dc8-b4a2-e74b4d571dbc)

Therefore I suggest that the 'clear all selections' button clears everything and takes me back to the new stakeholder start page.

Thanks!

**Comment by knirirr** [comment]
If the clear button were changed as suggested then it would break things for those who aren't using the questions. I'll have to think of something else.

**Comment by knirirr** [comment]
Fixed.
