### ISSUE TITLE
Breadcrumbs disappear when search results page is loaded

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/FAIRsharing-Assistant#99]
By keeping the breadcrumbs on the search result page, it is very easy for the user to go back to whatever section they need to, if they want to change their minds.

![image](https://github.com/FAIRsharing/FAIRsharing-Assistant/assets/143586/55b1cda8-ecb4-46b1-9b95-807ffd4d5ea6)

I suggest that we remove all 4 of the existing buttons on the search results page and replace them with the breadcrumbs. What do you think?

**Comment by knirirr** [comment]
Users are not necessarily going to reach this page from the questions and the breadcrumbs won't be relevant to them if they haven't. So, in some circumstances those buttons will have to remain.

**Comment by allysonlister** [comment]
Or the breadcrumbs could be introduced into the "all filters" page, where each time something is selected breadcrumbs appear. This would be ideal I think...?

**Comment by knirirr** [comment]
I'm not entirely sure what you mean by the "all filters" page, but if it's the research fields or the repository refinement page then I can't do breadcrumbs there. My plan is not to show any on those pages at all.
For the results page I could probably show them or not depending on whether the user has clicked on any questions.
